# Generated by Django 5.0 on 2026-05-20 06:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Crawler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="用户id")),
                ("user_name", models.CharField(max_length=50, verbose_name="用户名")),
                ("email", models.EmailField(max_length=254, verbose_name="邮箱")),
                ("spider_type", models.CharField(max_length=50, verbose_name="爬虫类型")),
                ("source", models.CharField(max_length=100, verbose_name="来源")),
                (
                    "action",
                    models.CharField(
                        choices=[("start", "启动"), ("stop", "停止")],
                        max_length=10,
                        verbose_name="操作",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "error_msg",
                    models.TextField(blank=True, null=True, verbose_name="异常信息"),
                ),
                ("is_success", models.BooleanField(default=True, verbose_name="是否成功")),
            ],
            options={
                "verbose_name": "爬虫任务",
                "verbose_name_plural": "爬虫任务",
                "db_table": "crawler_task",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SsrOneMovies",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("movies_type", models.CharField(max_length=120, verbose_name="来源网站")),
                ("name", models.CharField(max_length=200, verbose_name="名字")),
                (
                    "categories_str",
                    models.CharField(max_length=500, verbose_name="剧情类型"),
                ),
                ("region", models.CharField(max_length=100, verbose_name="上映地址")),
                ("duration", models.CharField(max_length=100, verbose_name="时长")),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, verbose_name="评分"
                    ),
                ),
                ("drama", models.TextField(verbose_name="剧情简介")),
                ("url", models.CharField(max_length=500, verbose_name="数据地址")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="抓取时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "电影数据",
                "verbose_name_plural": "电影数据",
                "db_table": "ssr_one_movies",
            },
        ),
    ]
