# Generated by Django 5.0 on 2026-05-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawler",
            name="error_url",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="异常URL"
            ),
        ),
    ]
