# Generated by Django 5.0 on 2026-06-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0002_crawler_error_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawler",
            name="completed_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="自然完成时间"),
        ),
        migrations.AddField(
            model_name="crawler",
            name="items_count",
            field=models.IntegerField(default=0, verbose_name="抓取数量"),
        ),
        migrations.AddField(
            model_name="crawler",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="任务开始时间"),
        ),
        migrations.AddField(
            model_name="crawler",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "运行中"),
                    ("completed", "已完成"),
                    ("stopped", "已停止"),
                    ("failed", "失败"),
                ],
                default="running",
                max_length=20,
                verbose_name="任务状态",
            ),
        ),
        migrations.AddField(
            model_name="crawler",
            name="stop_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="手动停止时间"),
        ),
        migrations.AddField(
            model_name="crawler",
            name="total_expected",
            field=models.IntegerField(default=0, verbose_name="预期总数"),
        ),
    ]
