# Generated by Django 5.0 on 2026-06-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0003_crawler_completed_time_crawler_items_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crawler",
            name="action",
        ),
        migrations.RemoveField(
            model_name="crawler",
            name="error_msg",
        ),
        migrations.RemoveField(
            model_name="crawler",
            name="error_url",
        ),
        migrations.RemoveField(
            model_name="crawler",
            name="is_success",
        ),
        migrations.AddField(
            model_name="crawler",
            name="error_info",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="异常信息，数据解构是列表【{字典}】"
            ),
        ),
    ]
