# Generated by Django 5.0 on 2026-06-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0004_remove_crawler_action_remove_crawler_error_msg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ssronemovies",
            name="release_date",
            field=models.DateField(blank=True, null=True, verbose_name="上映日期"),
        ),
    ]
