# Generated by Django 5.0 on 2026-06-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0005_ssronemovies_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ssronemovies",
            name="release_date",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="上映日期"
            ),
        ),
    ]
