# Generated by Django 5.0 on 2026-06-08 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0006_alter_ssronemovies_release_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ssronemovies",
            name="region",
        ),
    ]
