# Generated by Django 5.0 on 2026-03-18 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLoginLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "login_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="登录时间"),
                ),
                (
                    "logout_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="退出时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_log",
                        to="users.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "登录时间",
                "db_table": "users_login_log",
                "ordering": ["-login_time"],
            },
        ),
    ]
